language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kmlawlor/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kmlawlor/docker-react npm run test